import type { Product, Order, AdminStats, Review, Category } from "./types";

export const categories: Category[] = [
  { name: "All", slug: "all", count: 24 },
  { name: "Tees", slug: "tees", count: 8 },
  { name: "Hoodies", slug: "hoodies", count: 6 },
  { name: "Joggers", slug: "joggers", count: 4 },
  { name: "Outerwear", slug: "outerwear", count: 3 },
  { name: "Accessories", slug: "accessories", count: 3 },
];

export const products: Product[] = [
  {
    id: "1",
    name: "FORGED Tee",
    slug: "forged-tee",
    description:
      "Premium heavyweight cotton tee with the ASCEND FORGED emblem. Built for those who refuse to stay average. Every thread is a testament to discipline and resilience. This isn't just a t-shirt — it's a declaration of intent.",
    price: 49,
    comparePrice: 65,
    images: ["/products/forged-tee-1.jpg", "/products/forged-tee-2.jpg"],
    category: "tees",
    tags: ["new", "bestseller", "limited"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/forged-tee-1.jpg"] },
      { name: "Charcoal", hex: "#2D2D2D", images: ["/products/forged-tee-2.jpg"] },
    ],
    stock: 150,
    featured: true,
    new: true,
    rating: 4.9,
    reviewCount: 234,
    createdAt: "2025-01-15",
  },
  {
    id: "2",
    name: "PRESSURE Hoodie",
    slug: "pressure-hoodie",
    description:
      "Oversized premium hoodie with embossed PRESSURE branding. Triple-layer fleece construction with brushed interior. Designed to keep you warm through every storm.",
    price: 89,
    comparePrice: 120,
    images: ["/products/pressure-hoodie-1.jpg", "/products/pressure-hoodie-2.jpg"],
    category: "hoodies",
    tags: ["bestseller"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/pressure-hoodie-1.jpg"] },
      { name: "Slate", hex: "#4A4A4A", images: ["/products/pressure-hoodie-2.jpg"] },
    ],
    stock: 85,
    featured: true,
    new: false,
    rating: 4.8,
    reviewCount: 187,
    createdAt: "2025-01-10",
  },
  {
    id: "3",
    name: "ASCEND Runner Joggers",
    slug: "ascend-runner-joggers",
    description:
      "Technical joggers built for performance. Water-resistant coating, tapered fit, and reflective ASCEND branding. From the gym to the streets.",
    price: 79,
    comparePrice: 99,
    images: ["/products/runner-joggers-1.jpg", "/products/runner-joggers-2.jpg"],
    category: "joggers",
    tags: ["new"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/runner-joggers-1.jpg"] },
      { name: "Graphite", hex: "#3A3A3A", images: ["/products/runner-joggers-2.jpg"] },
    ],
    stock: 120,
    featured: true,
    new: true,
    rating: 4.7,
    reviewCount: 156,
    createdAt: "2025-02-01",
  },
  {
    id: "4",
    name: "NO LIMITS Bomber",
    slug: "no-limits-bomber",
    description:
      "Premium bomber jacket with satin lining. Military-grade hardware with ASCEND chain-stitch embroidery. Zero limits, zero excuses.",
    price: 149,
    comparePrice: 199,
    images: ["/products/bomber-1.jpg", "/products/bomber-2.jpg"],
    category: "outerwear",
    tags: ["limited"],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/bomber-1.jpg"] },
      { name: "Olive", hex: "#3D4A3D", images: ["/products/bomber-2.jpg"] },
    ],
    stock: 45,
    featured: true,
    new: false,
    rating: 5.0,
    reviewCount: 89,
    createdAt: "2024-12-20",
  },
  {
    id: "5",
    name: "RISE Heavyweight Tee",
    slug: "rise-heavyweight-tee",
    description:
      "220 GSM heavyweight cotton with oversized RISE graphic. Pre-shrunk, reinforced seams. The foundation of any premium wardrobe.",
    price: 55,
    images: ["/products/rise-tee-1.jpg", "/products/rise-tee-2.jpg"],
    category: "tees",
    tags: ["bestseller"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/rise-tee-1.jpg"] },
      { name: "White", hex: "#F5F5F5", images: ["/products/rise-tee-2.jpg"] },
      { name: "Charcoal", hex: "#2D2D2D", images: ["/products/rise-tee-1.jpg"] },
    ],
    stock: 200,
    featured: false,
    new: false,
    rating: 4.8,
    reviewCount: 312,
    createdAt: "2024-11-15",
  },
  {
    id: "6",
    name: "GRIND Tech Hoodie",
    slug: "grind-tech-hoodie",
    description:
      "Performance tech hoodie with 4-way stretch fabric. Moisture-wicking, anti-odor technology. Subtle tonal ASCEND branding.",
    price: 95,
    images: ["/products/grind-hoodie-1.jpg", "/products/grind-hoodie-2.jpg"],
    category: "hoodies",
    tags: ["new"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/grind-hoodie-1.jpg"] },
      { name: "Navy", hex: "#1A1A3E", images: ["/products/grind-hoodie-2.jpg"] },
    ],
    stock: 95,
    featured: false,
    new: true,
    rating: 4.6,
    reviewCount: 78,
    createdAt: "2025-02-10",
  },
  {
    id: "7",
    name: "UNBREAKABLE Cap",
    slug: "unbreakable-cap",
    description:
      "Premium structured snapback with embroidered UNBREAKABLE text. Adjustable strap with custom ASCEND metal hardware.",
    price: 35,
    images: ["/products/cap-1.jpg", "/products/cap-2.jpg"],
    category: "accessories",
    tags: ["bestseller"],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/cap-1.jpg"] },
    ],
    stock: 300,
    featured: false,
    new: false,
    rating: 4.7,
    reviewCount: 445,
    createdAt: "2024-10-01",
  },
  {
    id: "8",
    name: "EMPIRE Crossbody Bag",
    slug: "empire-crossbody-bag",
    description:
      "Water-resistant crossbody bag with hidden pockets. Heavy-duty YKK zippers and ASCEND rubber patch. Built for the grind.",
    price: 59,
    images: ["/products/bag-1.jpg", "/products/bag-2.jpg"],
    category: "accessories",
    tags: ["new"],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#0A0A0A", images: ["/products/bag-1.jpg"] },
      { name: "Coyote", hex: "#8B7355", images: ["/products/bag-2.jpg"] },
    ],
    stock: 75,
    featured: false,
    new: true,
    rating: 4.9,
    reviewCount: 67,
    createdAt: "2025-01-25",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    orderNumber: "ASC-2025-0001",
    customerName: "Ahmed Khan",
    phone: "+92 300 1234567",
    city: "Karachi",
    address: "DHA Phase 5, Street 12, House 45",
    notes: "Please deliver before 5 PM",
    items: [
      {
        productId: "1",
        productName: "FORGED Tee",
        size: "L",
        color: "Black",
        quantity: 2,
        price: 49,
      },
      {
        productId: "2",
        productName: "PRESSURE Hoodie",
        size: "M",
        color: "Black",
        quantity: 1,
        price: 89,
      },
    ],
    total: 187,
    status: "delivered",
    createdAt: "2025-01-20",
    updatedAt: "2025-01-25",
  },
  {
    id: "ord-002",
    orderNumber: "ASC-2025-0002",
    customerName: "Sara Malik",
    phone: "+92 321 7654321",
    city: "Lahore",
    address: "Gulberg III, Main Boulevard, Apt 12B",
    items: [
      {
        productId: "4",
        productName: "NO LIMITS Bomber",
        size: "M",
        color: "Black",
        quantity: 1,
        price: 149,
      },
    ],
    total: 149,
    status: "shipped",
    createdAt: "2025-02-01",
    updatedAt: "2025-02-03",
  },
  {
    id: "ord-003",
    orderNumber: "ASC-2025-0003",
    customerName: "Usman Ali",
    phone: "+92 333 1112233",
    city: "Islamabad",
    address: "F-8/2, House 22",
    items: [
      {
        productId: "3",
        productName: "ASCEND Runner Joggers",
        size: "XL",
        color: "Black",
        quantity: 1,
        price: 79,
      },
      {
        productId: "7",
        productName: "UNBREAKABLE Cap",
        size: "One Size",
        color: "Black",
        quantity: 2,
        price: 35,
      },
    ],
    total: 149,
    status: "confirmed",
    createdAt: "2025-02-05",
    updatedAt: "2025-02-05",
  },
  {
    id: "ord-004",
    orderNumber: "ASC-2025-0004",
    customerName: "Fatima Noor",
    phone: "+92 300 9876543",
    city: "Rawalpindi",
    address: "Satellite Town, Block C, House 7",
    items: [
      {
        productId: "5",
        productName: "RISE Heavyweight Tee",
        size: "S",
        color: "White",
        quantity: 3,
        price: 55,
      },
    ],
    total: 165,
    status: "pending",
    createdAt: "2025-02-08",
    updatedAt: "2025-02-08",
  },
];

export const mockReviews: Review[] = [
  {
    id: "rev-001",
    productId: "1",
    customerName: "Ahmed K.",
    rating: 5,
    comment:
      "Best quality tee I've ever owned. The weight of the fabric is incredible. You can feel the premium quality the moment you pick it up. ASCEND doesn't cut corners.",
    createdAt: "2025-01-25",
  },
  {
    id: "rev-002",
    productId: "1",
    customerName: "Bilal M.",
    rating: 5,
    comment:
      "The fit is perfect. Not too tight, not too loose. Exactly how a premium tee should fit. The embroidered logo is clean. This brand is going places.",
    createdAt: "2025-01-28",
  },
  {
    id: "rev-003",
    productId: "2",
    customerName: "Sara A.",
    rating: 5,
    comment:
      "This hoodie is a game changer. The fleece interior is so soft and the oversized fit is exactly what I wanted. Worth every penny.",
    createdAt: "2025-02-01",
  },
  {
    id: "rev-004",
    productId: "2",
    customerName: "Usman R.",
    rating: 4,
    comment:
      "Great hoodie overall. The quality is top notch. Only giving 4 stars because I wish there were more color options. Waiting for a navy drop!",
    createdAt: "2025-02-03",
  },
  {
    id: "rev-005",
    productId: "4",
    customerName: "Zainab F.",
    rating: 5,
    comment:
      "This bomber is museum quality. The satin lining, the embroidery, the hardware — everything screams premium. People stop me to ask where I got it.",
    createdAt: "2025-02-05",
  },
];

export const adminStats: AdminStats = {
  totalOrders: 47,
  totalRevenue: 8943,
  totalCustomers: 34,
  conversionRate: 3.8,
  topProducts: [
    { name: "FORGED Tee", sold: 89 },
    { name: "PRESSURE Hoodie", sold: 67 },
    { name: "UNBREAKABLE Cap", sold: 134 },
    { name: "RISE Heavyweight Tee", sold: 56 },
    { name: "NO LIMITS Bomber", sold: 23 },
  ],
  dailySales: [
    { date: "Mon", amount: 1240 },
    { date: "Tue", amount: 890 },
    { date: "Wed", amount: 1560 },
    { date: "Thu", amount: 1120 },
    { date: "Fri", amount: 2100 },
    { date: "Sat", amount: 1890 },
    { date: "Sun", amount: 1340 },
  ],
};

export const testimonials = [
  {
    name: "Ahmed Khan",
    location: "Karachi",
    quote:
      "ASCEND isn't just a brand — it's a mindset. The quality speaks for itself, but the message behind it is what keeps me coming back.",
    rating: 5,
  },
  {
    name: "Sara Malik",
    location: "Lahore",
    quote:
      "Finally a brand that matches the energy of the gym. The PRESSURE Hoodie is my daily essential. Premium quality at a fair price.",
    rating: 5,
  },
  {
    name: "Bilal Ahmed",
    location: "Islamabad",
    quote:
      "The attention to detail is insane. From the packaging to the stitching — everything feels intentional. ASCEND sets the standard.",
    rating: 5,
  },
  {
    name: "Zainab Fatima",
    location: "Rawalpindi",
    quote:
      "Wore the NO LIMITS Bomber to a business meeting and got more compliments than anyone in the room. That's the ASCEND effect.",
    rating: 5,
  },
  {
    name: "Usman Ali",
    location: "Multan",
    quote:
      "I've tried dozens of streetwear brands. None come close to ASCEND in terms of fabric quality and fit. This is the one.",
    rating: 5,
  },
];
